In [36]:
import pandas as pd
import numpy as np
#Transformasi data
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [20]:
bigprojek =pd.read_csv("D:/Kuliah/In/SSD/Big Project Progress Data_Kelompok 8.csv")
bigprojek

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [21]:
bigprojek.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          2111 non-null   object
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   object
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CALC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [22]:
bigprojek.drop_duplicates(inplace=True)

In [23]:
df_projek = bigprojek.copy()

In [24]:
x = df_projek.drop(columns=["NObeyesdad"])
y = df_projek["NObeyesdad"]

In [25]:
from sklearn.model_selection import train_test_split

#Split dataset into training set and test set
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [26]:
#Transformasi data dengan Standard Scaler
columns = ['Age','Height','Weight','FCVC','NCP','CH2O','FAF','TUE']
scaler = StandardScaler()
X_train_scale = scaler.fit_transform(x_train[columns])
X_test_scale = scaler.transform(x_test[columns])

x_train[columns]=X_train_scale
x_test[columns]=X_test_scale

In [54]:
x_test

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE,Gender,family_history_with_overweight,FAVC,CAEC,SCC,CALC,MTRANS,SMOKE
305,-0.199447,0.534148,1.279380,-0.813012,0.398305,-0.022179,1.171759,0.546565,1,1,1,2,0,1,3,1
386,-0.980893,-1.201101,-1.268195,-2.691952,0.398305,-1.668779,-0.007637,2.186246,0,0,0,2,0,2,3,0
1021,-0.406819,-2.177179,-0.863156,-0.813012,-1.601724,-0.022179,-0.862891,-0.086513,0,1,0,2,0,2,3,0
1625,0.166489,0.935392,1.090226,-0.813895,0.398305,0.162089,0.526679,0.299798,1,1,1,2,0,1,3,0
270,-0.199447,1.293320,0.785074,-0.813012,0.398305,1.624422,-1.187034,0.546565,1,0,1,2,0,1,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
366,1.363447,0.208789,-0.127490,-0.813012,-2.224402,-0.022179,2.351156,-1.093116,1,1,1,2,0,1,0,0
2019,0.268045,-0.893658,0.706967,1.065928,0.398305,0.720866,-1.135507,0.006129,0,1,1,2,0,1,3,0
757,-0.379957,-0.944414,-0.693015,-1.266975,1.686050,0.264738,-0.101428,1.133838,0,1,1,2,0,1,3,0
2064,-0.515438,0.220252,1.737745,1.065928,0.398305,-0.551082,0.797289,0.249571,0,1,1,2,0,1,3,0
461,-0.512025,0.100336,0.518910,-0.813012,-2.224402,-0.022179,-1.187034,2.186246,1,1,1,2,0,2,3,0

In [27]:
#membuat transformasi endcoder
le = LabelEncoder()
label_x_train = le.fit_transform(x_train['Gender'])
label_x_test = le.fit_transform(x_test['Gender'])
x_train.drop('Gender', axis=1, inplace=True)
x_test.drop('Gender', axis=1, inplace=True)
x_train['Gender'] = label_x_train
x_test['Gender'] = label_x_test

In [28]:
le = LabelEncoder()
label_x_train = le.fit_transform(x_train['family_history_with_overweight'])
label_x_test = le.fit_transform(x_test['family_history_with_overweight'])
x_train.drop('family_history_with_overweight', axis=1, inplace=True)
x_test.drop('family_history_with_overweight', axis=1, inplace=True)
x_train['family_history_with_overweight'] = label_x_train
x_test['family_history_with_overweight'] = label_x_test

In [29]:
le = LabelEncoder()
label_x_train = le.fit_transform(x_train['FAVC'])
label_x_test = le.fit_transform(x_test['FAVC'])
x_train.drop('FAVC', axis=1, inplace=True)
x_test.drop('FAVC', axis=1, inplace=True)
x_train['FAVC'] = label_x_train
x_test['FAVC'] = label_x_test

In [30]:
le = LabelEncoder()
label_x_train = le.fit_transform(x_train['CAEC'])
label_x_test = le.fit_transform(x_test['CAEC'])
x_train.drop('CAEC', axis=1, inplace=True)
x_test.drop('CAEC', axis=1, inplace=True)
x_train['CAEC'] = label_x_train
x_test['CAEC'] = label_x_test

In [31]:
le = LabelEncoder()
label_x_train = le.fit_transform(x_train['SCC'])
label_x_test = le.fit_transform(x_test['SCC'])
x_train.drop('SCC', axis=1, inplace=True)
x_test.drop('SCC', axis=1, inplace=True)
x_train['SCC'] = label_x_train
x_test['SCC'] = label_x_test

In [32]:
le = LabelEncoder()
label_x_train = le.fit_transform(x_train['CALC'])
label_x_test = le.fit_transform(x_test['CALC'])
x_train.drop('CALC', axis=1, inplace=True)
x_test.drop('CALC', axis=1, inplace=True)
x_train['CALC'] = label_x_train
x_test['CALC'] = label_x_test

In [39]:
le = LabelEncoder()
label_x_train = le.fit_transform(x_train['SMOKE'])
label_x_test = le.fit_transform(x_test['SMOKE'])
x_train.drop('SMOKE', axis=1, inplace=True)
x_test.drop('SMOKE', axis=1, inplace=True)
x_train['SMOKE'] = label_x_train
x_test['SMOKE'] = label_x_test

In [33]:
le = LabelEncoder()
label_x_train = le.fit_transform(x_train['MTRANS'])
label_x_test = le.fit_transform(x_test['MTRANS'])
x_train.drop('MTRANS', axis=1, inplace=True)
x_test.drop('MTRANS', axis=1, inplace=True)
x_train['MTRANS'] = label_x_train
x_test['MTRANS'] = label_x_test

In [34]:
#TRANSFORMASI Y TRAIN
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.fit_transform(y_test)

In [40]:
x_train

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE,Gender,family_history_with_overweight,FAVC,CAEC,SCC,CALC,MTRANS,SMOKE
1971,-0.778186,1.263723,2.112771,1.065928,0.398305,1.129906,0.606614,0.159584,0,1,1,2,0,2,3,0
2054,-0.510729,0.247691,1.732989,1.065928,0.398305,-0.543414,0.753701,0.313827,0,1,1,2,0,2,3,0
470,-0.668315,-1.526460,-1.325230,-0.813012,0.398305,-0.022179,2.351156,-1.093116,0,0,1,1,0,2,3,0
1139,-0.342130,0.994369,0.138626,-0.992015,-0.115200,-1.332585,-1.187034,2.014591,1,1,1,2,0,2,3,0
223,-0.355736,-0.984195,-0.887960,1.065928,0.398305,1.624422,-0.007637,-1.093116,0,1,1,1,0,3,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057,0.026367,0.196263,-0.001256,-0.813012,-0.024353,1.120526,-1.187034,0.035006,1,1,1,2,0,2,3,0
1755,-0.237113,1.724063,1.328222,0.415958,-0.160190,-0.376676,0.193494,-1.093116,1,1,1,2,0,2,3,0
778,0.325517,0.591813,-0.156814,-0.919867,1.132454,0.583763,-0.909251,0.349765,1,1,1,2,0,2,3,0
856,0.566337,-0.008117,-0.460423,-0.813012,0.398305,-0.022179,0.843950,-1.093116,0,1,1,2,0,2,0,0
1677,0.911492,1.530919,1.434163,0.065483,0.398305,1.065055,-0.014216,-0.584169,1,1,1,2,0,2,3,0

In [49]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
rfc = RandomForestClassifier()

rfc.fit(x_train, y_train)
y_pred8 = rfc.predict(x_test)
score8 = metrics.accuracy_score(y_test, y_pred8)
print("Akurasi dengan menggunakan Random Forest: ", score8)

Akurasi dengan menggunakan Random Forest:  0.9617224880382775

In [52]:
import pickle
fillname1="RFC_model.pkl"
pickle.dump(rfc, open(fillname1,"wb"))

In [53]:
import pickle
fillname1="Scaler_model.pkl"
pickle.dump(scaler, open(fillname1,"wb"))